# Usa a imagem oficial do DeepStream (ideal para o seu Ubuntu com GPU)
FROM nvcr.io/nvidia/deepstream:6.3-triton-multiarch

ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHONUNBUFFERED=1
ENV CUDA_VER=12.1

RUN apt-get update && apt-get install -y \
    python3-gi \
    python3-dev \
    python3-gst-1.0 \
    git \
    python3 \
    python3-pip \
    python3-venv \
    cmake \
    g++ \
    build-essential \
    libglib2.0-dev \
    libglib2.0-dev-bin \
    libgstreamer1.0-dev \
    libtool \
    m4 \
    autoconf \
    automake \
    libgirepository1.0-dev \
    libcairo2-dev \
    && rm -rf /var/lib/apt/lists/*
    
WORKDIR /app


RUN pip3 install --upgrade pip && \
    pip3 install onnx onnxsim onnxruntime opencv-python-headless && \
    pip3 install https://github.com/NVIDIA-AI-IOT/deepstream_python_apps/releases/download/v1.1.8/pyds-1.1.8-py3-none-linux_x86_64.whl
COPY . .
WORKDIR /app/DeepStream-Yolo/nvdsinfer_custom_impl_Yolo
RUN CUDA_VER=12.1 make
WORKDIR /app
ENV PYTHONUNBUFFERED=1
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/nvidia/deepstream/deepstream/lib
ENTRYPOINT ["python3"]
CMD ["deepstream_app.py"]